# Describes the format for available saj_mqtt services

# Read a register value from the inverter
read_register:
  description: Read a register value from the inverter
  fields:
    config_entry:
      name: Device
      description: SAJ H1 solar inverter, defaults to the first configured device if not specified
      required: false
      selector:
        config_entry:
          integration: saj_h1_mqtt
    register:
      name: Register
      description: The register address in hex or decimal format
      example: "0x3247 (hex) or 12871 (decimal)"
      required: true
      selector:
        text:
    register_size:
      name: Register size
      description: The size of the register in hex or decimal format
      example: "0x1 (hex) or 1 (decimal)"
      required: true
      selector:
        text:
    register_format:
      name: Register format
      description: The register output format (python struct format)
      example: ">H"
      required: false
      selector:
        text:

# Write a register value to the inverter
write_register:
  description: Write a register value to the inverter
  fields:
    config_entry:
      name: Device
      description: SAJ H1 solar inverter, defaults to the first configured device if not specified
      required: false
      selector:
        config_entry:
          integration: saj_h1_mqtt
    register:
      name: Register
      description: The register address in hex or decimal format
      example: "0x3247 (hex) or 12871 (decimal)"
      required: true
      selector:
        text:
    register_value:
      name: Register value
      description: The register value in hex or decimal format
      example: "0x1 (hex) or 1 (decimal)"
      required: true
      selector:
        text:

# Refresh the inverter data sensors
refresh_inverter_data:
  description: Refresh the inverter data sensors
  fields:
    config_entry:
      name: Device
      description: SAJ H1 solar inverter, defaults to the first configured device if not specified
      required: false
      selector:
        config_entry:
          integration: saj_h1_mqtt

# Refresh the battery data sensors
refresh_battery_data:
  description: Refresh the battery data sensors
  fields:
    config_entry:
      name: Device
      description: SAJ H1 solar inverter, defaults to the first configured device if not specified
      required: false
      selector:
        config_entry:
          integration: saj_h1_mqtt

# Refresh the battery controller data sensors
refresh_battery_controller_data:
  description: Refresh the battery controller data sensors
  fields:
    config_entry:
      name: Device
      description: SAJ H1 solar inverter, defaults to the first configured device if not specified
      required: false
      selector:
        config_entry:
          integration: saj_h1_mqtt

# Refresh the config data sensors
refresh_config_data:
  description: Refresh the config data sensors
  fields:
    config_entry:
      name: Device
      description: SAJ H1 solar inverter, defaults to the first configured device if not specified
      required: false
      selector:
        config_entry:
          integration: saj_h1_mqtt
